### PR TITLE
bumping go 1.22 to go 1.23

### PR DESCRIPTION
**Pull request by 7h3-3mp7y-m4n**
#### Description

Did the changes as mentioned at #179 
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New chore (expected functionality to be implemented)

#### Checklist:

- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] I've signed off with an email address that matches the commit author.

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
@7h3-3mp7y-m4n, CI/test is not running on the PR, because of this https://github.com/score-spec/score-compose/commit/16cab8714dc54e675591a7fe1dba3175aa36edee, could you please re-sync your branch in your fork with upstream's `main` branch please? Thanks!

**Review by mathieu-benoit — APPROVED** [review]
CI/test passing successfully, LGTM, thanks for your contribution!
https://github.com/score-spec/score-compose/actions/runs/11315374656/job/31466472345?pr=181

**Comment by mathieu-benoit** [comment]
@delca85, could you please give this a quick review in case we are missing anything here? Thanks!

**Review by delca85 — APPROVED** [review]
👍

**Pull request merged**
