### PR TITLE
feat: added postgres provisioner

### PR DESCRIPTION
**Pull request by astromechza**
This PR adds a default postgres database provisioner to score-compose.

No parameters are needed, and this provisioner will setup:

- shared database instance with unique service name and root password
- a file containing a script to generate a unique database, user name, and password per resource
- a second init service which connects to the database and run the scripts once it is healthy

All data is stored on a docker volume and persists between restarts.

NOTE: databases will not be removed if they are no longer referenced. Like most other resources, you must `rm -rf .score-compose; score-compose init; score-compose generate score.yaml` to reset the resources.

Some modifications were needed to the template provisioner to support the custom Go types used in the compose structures that were not encountered before.

An info log is output giving instructions for connecting manually to the db either via a temporary docker container or via a pq client:

```
INFO: postgres.default#example.db: To connect to postgres, enter password 'H5gLM9Qr1s1Dd325' at: "docker run -it --network temptest_default --rm postgres:16-alpine psql -h pg-VmK5s6 -U user-FjgMPoQq --dbname db-QrpRCLQz"
INFO: postgres.default#example.db: Or connect your postgres client to postgres://user-FjgMPoQq:H5gLM9Qr1s1Dd325@localhost:15432/db-QrpRCLQz
```

The latter is only available if the following annotation is given:

```
resources:
  db:
    type: postgres
    metadata:
      annotations:
        compose.score.dev/publish-port: "15432"
```

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
So this will typically allow this: https://github.com/score-spec/sample-score-app/pull/16, right?

**Comment by astromechza** [comment]
> So this will typically allow this: [score-spec/sample-score-app#16](https://github.com/score-spec/sample-score-app/pull/16), right?

@mathieu-benoit can you clarify what you mean, this PR just enables the type=postgres resource

**Comment by docktorrr** [comment]
Should we have tests for different provisioners? At least popular ones?

**Comment by astromechza** [comment]
> Should we have tests for different provisioners? At least popular ones?

Yup, currently adding some missing tests now. Thanks for reminding me!

**Comment by mathieu-benoit** [comment]
> > So this will typically allow this: [score-spec/sample-score-app#16](https://github.com/score-spec/sample-score-app/pull/16), right?
> 
> @mathieu-benoit can you clarify what you mean, this PR just enables the type=postgres resource

Sorry for the confusion, what I meant is that once this `score-compose init|generate` is available, this will simplify the `sample-score-app` setup because of this: https://github.com/score-spec/sample-score-app/blob/score-compose-generate/score.yaml#L30. Does this clarify?

**Comment by astromechza** [comment]
> > > So this will typically allow this: [score-spec/sample-score-app#16](https://github.com/score-spec/sample-score-app/pull/16), right?
> > 
> > 
> > @mathieu-benoit can you clarify what you mean, this PR just enables the type=postgres resource
> 
> Sorry for the confusion, what I meant is that once this `score-compose init|generate` is available, this will simplify the `sample-score-app` setup because of this: [score-spec/sample-score-app@`score-compose-generate`/score.yaml#L30](https://github.com/score-spec/sample-score-app/blob/score-compose-generate/score.yaml?rgh-link-date=2024-03-12T17%3A13%3A50Z#L30). Does this clarify?

Right, yes it will simplify that a lot, although we don't yet support the dns and route resource so you'd need to provide your own provisioner statements for those. Something like:

```
- uri: template://custom-dns
  type: dns
  outputs: "{}"
- uri: template://custom-route
  type: route
  outputs: "{}"
```

**Review by docktorrr — APPROVED** [review]
LGTM

**Pull request merged**
